// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    passthrough
    (
        init => init
        upgrade => upgrade
        getMultisigAddress => multisig_address
        addInteraction => add_interaction
        disableInteraction => disable_interaction
        enableInteraction => enable_interaction
        addAllowedAddresses => add_allowed_addresses
        setAllowedTokenForInteraction => set_allowed_token_for_interaction
        canExecute => can_execute
        getAllowedUsersForInteraction => get_allowed_users_for_interaction
        getAllowedTokenForInteraction => get_allowed_token_for_interaction
        getInteractionStatus => get_interaction_status
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
